Using libmpdel to get mpd information
manateelazycat/awesome-tray pull request #71
Opened 2022-06-18 22:25 UTC by LucasTavaresA

2022-06-18 22:45 UTC, manateelazycat requested changes

2022-06-18 22:45 UTC, manateelazycat commented on awesome-tray.el
> +  (if (executable-find "mpd")
Use (if (and (ignore-errors (require 'libmpdel)) (executable-find "mpd") ...) instead.

We should use `ignore-errors (require 'xxx)``` check third-part library is installed dynamically.

2022-06-18 22:45 UTC, manateelazycat commented on awesome-tray.el
> +;; `libmpdel'
Remove this line, awesome-tray shouldn't depend any third-part library

2022-06-18 22:45 UTC, manateelazycat commented on awesome-tray.el
> +(require 'libmpdel nil t)
Remove this line, awesome-tray shouldn't depend any third-part library

2022-06-18 23:15 UTC, LucasTavaresA commented
wait its not working

2022-06-18 23:25 UTC, manateelazycat commented
Works now?

2022-06-18 23:37 UTC, LucasTavaresA commented
its working fine, but using `(awesome-tray-mode 1)` gives me the error (invalid-read-syntax ) 1 0)

2022-06-18 23:41 UTC, manateelazycat commented
toggle-debug-on-error

2022-06-18 23:52 UTC, LucasTavaresA commented
[debug log](https://pastebin.com/vu9afJSN)

2022-06-18 23:56 UTC, LucasTavaresA commented
im using doom emacs, i used the same config but the problem is in this branch only

2022-06-19 00:10 UTC, LucasTavaresA commented
put way to much parenthesis
but its ready now

2022-06-19 01:48 UTC, merged

2022-06-19 01:48 UTC, manateelazycat commented
Looks good, thanks for patch.